### ISSUE TITLE
Corrections and elaborations to the protocol description

### ISSUE THREAD

**Issue by KerJoe** [v1993/cemuhook-protocol#1] opened 2019-12-23 19:17 UTC
Hello, your cemuhook protocol reference was a lot of help, yet there are some things which I think can be improved upon and elaborated.
1. The controller's data outgoing message, is not described correctly and actually lacks 5 bytes of data. Here is how it seems to actually go:

| Offset | Length | Type | Meaning |
| ------ | ------ | ---- | ------- |
| 0  | 11 | Complex | Beginning described above |
| **11** | **1** | **Byte** | **Controller state: 1 if active, 0 if not** |
| **12** | **4** | **Unsigned 32-bit** | **Packet number** |
| 16 | 1 | Bitmask | D-Pad Left, D-Pad Down, D-Pad Right, D-Pad Up, Options (?), R3, L3, Share (?) |
| ... | ... | ... | ... |
| 80 | 4 | Float | Gyroscope roll |
2. I think it would be nice to clarify that:
 - For the accelerometer readings g = 1.0f (not g = 9.8f). So the accelerometer typically outputs data from -1.0f to 1.0f.
 - The motion data timestemp seems to be measured in milliseconds.

**Comment by v1993** [comment] 2019-12-23 19:26
Glad it helped you!

1. Going to check that. I remember packet counter thingy, so looks like I missed it here. Thanks for pointing out!
2. Yep, you make a point here. Have to do it (did I got accelerometer range right myself in linuxmotehook tho?..).

Please ping me in few days if I'll forget about this issue.

**Comment by v1993** [comment] 2019-12-23 19:53
Are you sure about accelerometer thing? I remember asking cemuhook dev and he said that it's simply physical units, so g = 9.8f.

**Comment by KerJoe** [comment] 2019-12-23 19:56
I got the g=1f thing from the Android MotionSource server using PadTest.

**Comment by v1993** [comment] 2019-12-23 20:10
Hmm, interesting. I probably should ask rajkosto (cemuhook dev) directly to be 100% sure.

**Comment by KerJoe** [comment] 2019-12-23 20:13
I have also tried passing (0f, 0f, 1f) and (1f, 0f, 0f) to the PadTest via a UDP server programm on pc and  the 3d view of a controller was lying horizontally and on its side respectevely.
![padTest](https://user-images.githubusercontent.com/40915672/71378681-2d3c8900-25e2-11ea-8f8c-b46e21f5cb56.png)

**Comment by v1993** [comment] 2019-12-23 20:16
Yep, just asked rajkosto on discord and yes, you're right. Going to add changes tomorrow, it's late here.

**Comment by KerJoe** [comment] 2019-12-23 20:26
I have also just remeasured the time stamp data from the android app and it seems that it actually is measured in microseconds not miliseconds
![timeStamp](https://user-images.githubusercontent.com/40915672/71379192-dd5ec180-25e3-11ea-81ac-7ee4390f029a.png)

**Comment by v1993** [comment] 2020-02-02 16:26
Oh, sorry. I'm going for this now.

**Comment by v1993** [comment] 2020-02-02 16:41
Should last line be

```
| 76 | 4 | Float | Gyroscope roll |
```
?

I think the whole thing got shifted by five.

**Comment by v1993** [comment] 2020-02-02 16:52
Also, I think timestamp is in microseconds, not milliseconds? Need to make sure, but it seems to be.

**Comment by v1993** [comment] 2020-02-02 17:07
Yes, rajkosto confirmed that it is in microseconds.

**Comment by v1993** [comment] 2020-02-02 17:14
Should be fixed now. Please write if there are any more issues!

**Closed as completed by v1993** 2020-02-02 17:14 UTC
